MyFirstAppCSharp.Web/Models/ErrorViewModel.cs
using System;

namespace MyFirstAppCSharp.Web.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyFirstAppCSharp.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyFirstAppCSharp.Web.Models;

namespace MyFirstAppCSharp.Web.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyFirstAppCSharp.Web/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using MyFirstAppCSharp.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyFirstAppCSharp.Service;
using MyFirstAppCSharp.Data.Data;
using MyFirstAppCSharp.Data.Model;
using Newtonsoft.Json;

namespace MyFirstAppCSharp.Web.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly RestaurantsContext _context;

        public RestaurantsController(RestaurantsContext context)
        {
            _context = context;
        }
        

        // Connecion a la base de donnée + affichage des restaurants
        public async Task<IActionResult> Index()
        {
            _context.Database.EnsureCreated();  // Créer la base de donnée avec les tables et nom qui sont dans Restaurant.cs Adress.cs et Grade.cs dans le dossier Model 
            _context.Restaurant.Include(x => x.address);
            RestaurantService restaurantService = new RestaurantService(_context);

            var result = restaurantService.Get();
            return View(result);
        }
        
        // Récupère le détail des restaurants 
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            _context.Restaurant.Include(x => x.address);
            var restaurant = await _context.Restaurant.Include(x => x.address)
                .FirstOrDefaultAsync(m => m.ID == id);

            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // Affiche la page de création 
        public IActionResult Create()
        {
            return View();
        }
        

        public void JsonToSQL(string JSONresult)
        {

        }


        // Créer un nouveau restraurant 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,NumeroTel, Description, EmailProprio,address,  address.street")] Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                _context.Restaurant.Include(x => x.address);
                RestaurantService restaurantService = new RestaurantService(_context);
                restaurantService.AjouterRestau(restaurant);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        
        // Affiche la page d'édition
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View();
        }
        
        // Edition d'un restaurant
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID, Name,NumeroTel, Description, EmailProprio, address, address.street")] Restaurant restaurant)
        {
            if (id != restaurant.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    RestaurantService restaurantService = new RestaurantService(_context);
                    restaurantService.EditRestau(restaurant);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurant.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(restaurant);
        }
        
        // Supprime un restaurant
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant
                .FirstOrDefaultAsync(m => m.ID == id);
            RestaurantService restaurantService = new RestaurantService(_context);
            restaurantService.SupprRestau(restaurant);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }
        
        // Redirection de l'utilisateur après suppresion d'un restaurant
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var restaurant = await _context.Restaurant.FindAsync(id);
            
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
            return _context.Restaurant.Any(e => e.ID == id);
        }
    }
}

MyFirstAppCSharp.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Trouve ou ajoute ton restaurant dans l'onglet restaurant</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">Classement disponible</a>.</p>
</div>

MyFirstAppCSharp.Web/Views/Restaurants/Create.cshtml
@model MyFirstAppCSharp.Data.Model.Restaurant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" type="text" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroTel" class="control-label"></label>
                <input asp-for="NumeroTel" class="form-control" type="text" />
                <span asp-validation-for="NumeroTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" type="text" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailProprio" class="control-label"></label>
                <input asp-for="EmailProprio" class="form-control" type="text" />
                <span asp-validation-for="EmailProprio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.street" class="control-label"></label>
                <input asp-for="address.street" class="form-control" type="text" />
                <span asp-validation-for="address.street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstAppCSharp.Web/Views/Restaurants/Delete.cshtml
@model MyFirstAppCSharp.Data.Model.Restaurant

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroTel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumeroTel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmailProprio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmailProprio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyFirstAppCSharp.Web/Views/Restaurants/Details.cshtml
@model MyFirstAppCSharp.Data.Model.Restaurant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumeroTel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumeroTel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EmailProprio)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EmailProprio)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.address.street)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyFirstAppCSharp.Web/Views/Restaurants/Edit.cshtml
@model MyFirstAppCSharp.Data.Model.Restaurant

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Restaurant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumeroTel" class="control-label"></label>
                <input asp-for="NumeroTel" class="form-control" />
                <span asp-validation-for="NumeroTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmailProprio" class="control-label"></label>
                <input asp-for="EmailProprio" class="form-control" />
                <span asp-validation-for="EmailProprio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address.street" class="control-label"></label>
                <input asp-for="address.street" class="form-control" />
                <span asp-validation-for="address.street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFirstAppCSharp.Web/Views/Restaurants/Index.cshtml
@model IEnumerable<MyFirstAppCSharp.Data.Model.Restaurant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeroTel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailProprio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address.street)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)

        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeroTel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmailProprio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address.street)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

MyFirstAppCSharp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstAppCSharp.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstAppCSharp.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurants" asp-action="Index">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - MyFirstAppCSharp.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>